# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiniProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiniProject
   
  pod 'SwiftyJSON', '5.0.1'
  pod 'SnapKit'

target 'MiniProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiniProjectUITests' do
    # Pods for testing
  end

end
